In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


#### 1D array ---Vector Array

In [3]:
import numpy as np

numpy_array=np.array([1,2,3,4,5])
print(numpy_array)
type(numpy_array)

[1 2 3 4 5]


numpy.ndarray

#### 2D Array --- matrix

In [4]:
twod_array=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(twod_array)
type(twod_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


numpy.ndarray

3D Array

In [5]:
threeDArray=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(threeDArray)
type(threeDArray)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


numpy.ndarray

#### np.array()---use to create multidimensional array

#### dtype parameter ---> which can help us out deciding about the size of the data we are going to store inside our array
#### dtype=bool,int,float

In [6]:
np.array([1,2,3,4,5],dtype=np.int64)
np.array([1,2,3,4,5],dtype=np.int32)

array([1, 2, 3, 4, 5], dtype=int32)

#### by old range() function

In [7]:
empty_list=[]
for i in range(16):
    empty_list.append(i)
print(empty_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


#### arange() ---- it helps us out with providing the values over a certain range

In [8]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [9]:
np.arange(5,21)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [10]:
## skip by two values
np.arange(2,21,2)
## last two here is for skiping values in 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

#### np.reshape()---> it help us out with changing the shape of the array as per our need

In [13]:
### reshape the data in 4*4
arrange_data=np.arange(1,17)
arrange_data.reshape(4,4)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [14]:
arrange_data.reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [15]:
np.arange(2,17,2).reshape(4,2)

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

#### ones() --->
#### zeros()---->

In [ ]:
np.ones((4,4)) #--Inside it is a tuple(4,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.zeros((4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

#### random()---it help us out with generating any random values from 0 to 1 inside our matrix

In [19]:
np.random.random((3,4))

array([[0.123363  , 0.76591501, 0.7362904 , 0.5620313 ],
       [0.18525582, 0.05783311, 0.50557377, 0.7337005 ],
       [0.55740404, 0.31550232, 0.47747291, 0.21812215]])

#### identity()--> it help us out with creating the matrix as an identity matrix (square matrix--> rows=column)

In [22]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### linespace()---->it make sure that every value with in the given range is going to have similer distance to each other

In [24]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

# Attributes
#### ndim ---> it stands for n-dimension


In [27]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [28]:
arr.ndim

1

In [29]:
arrayy=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [31]:
arrayy.ndim

3

#### shape--->it provide us with the idea about the rows and column in our data set or in array

In [33]:
np.array([[1,2,3],[4,5,6],[7,8,9]]).shape

(3, 3)

In [34]:
np.array([[[1,2],[3,4]],[[1,2],[3,4]]]).shape

(2, 2, 2)

#### size--->size attribute provide the idea total number of elements present inside our dataset or array

In [36]:
np.array([[1,2,3],[4,5,6]]).size

6

In [37]:
np.arange(5,57).size

52

#### itemsize --->provide with the idea about the size of a unique elements inside our array in bytes

In [39]:
np.array([[1,2],[3,4],[5,6]],dtype=np.int32).itemsize

4

#### dtype-->it provide us with the idea about the type of every item inside our array by default it is int64

In [40]:
np.array([[1,2,3],[4,5,6],[7,8,9]]).dtype

dtype('int64')