#### astype()---> will be helping us out with figuring out the data type of the column in the dataset in pandas and it will be used in numpy  as well for getting the data type changed of our overall array

In [1]:
import numpy as np

ary=np.arange(1,10).reshape(3,3)
ary

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
ary.astype('float64')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [3]:
type(ary)

numpy.ndarray

In [5]:
ary.dtype

dtype('int64')

#### Mathemetical operation in Numpy

#### scalar Operations---> a scaler value will be operation will be done with the array or a numeric value(eg. 1,4)

In [10]:
array=np.random.random((3,3))*100
array=np.round(array)
array=array.astype('int32')
array

array([[54, 85, 38],
       [73, 66, 10],
       [47, 48, 33]], dtype=int32)

In [11]:
array+2


array([[56, 87, 40],
       [75, 68, 12],
       [49, 50, 35]], dtype=int32)

In [12]:
array-5

array([[49, 80, 33],
       [68, 61,  5],
       [42, 43, 28]], dtype=int32)

In [13]:
array*2

array([[108, 170,  76],
       [146, 132,  20],
       [ 94,  96,  66]], dtype=int32)

In [14]:
array/2

array([[27. , 42.5, 19. ],
       [36.5, 33. ,  5. ],
       [23.5, 24. , 16.5]])

In [15]:
array*2

array([[108, 170,  76],
       [146, 132,  20],
       [ 94,  96,  66]], dtype=int32)

### we can apply the scalar operation with the array in terms of arithmetic operation

In [16]:
array>60


array([[False,  True, False],
       [ True,  True, False],
       [False, False, False]])