#### astype()---> will be helping us out with figuring out the data type of the column in the dataset in pandas and it will be used in numpy  as well for getting the data type changed of our overall array

In [1]:
import numpy as np

ary=np.arange(1,10).reshape(3,3)
ary

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
ary.astype('float64')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [3]:
type(ary)

numpy.ndarray

In [5]:
ary.dtype

dtype('int64')

#### Mathemetical operation in Numpy

#### scalar Operations---> a scaler value will be operation will be done with the array or a numeric value(eg. 1,4)

In [10]:
array=np.random.random((3,3))*100
array=np.round(array)
array=array.astype('int32')
array

array([[54, 85, 38],
       [73, 66, 10],
       [47, 48, 33]], dtype=int32)

In [11]:
array+2


array([[56, 87, 40],
       [75, 68, 12],
       [49, 50, 35]], dtype=int32)

In [12]:
array-5

array([[49, 80, 33],
       [68, 61,  5],
       [42, 43, 28]], dtype=int32)

In [13]:
array*2

array([[108, 170,  76],
       [146, 132,  20],
       [ 94,  96,  66]], dtype=int32)

In [14]:
array/2

array([[27. , 42.5, 19. ],
       [36.5, 33. ,  5. ],
       [23.5, 24. , 16.5]])

In [15]:
array*2

array([[108, 170,  76],
       [146, 132,  20],
       [ 94,  96,  66]], dtype=int32)

### we can apply the scalar operation with the array in terms of arithmetic operation

In [16]:
array>60


array([[False,  True, False],
       [ True,  True, False],
       [False, False, False]])

#### Vector operation---> operation will be in between the given number of matrices


In [17]:
arr=np.arange(1,17).reshape(4,4)

In [18]:
arr_2=np.arange(17,33).reshape(4,4)

In [19]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [20]:
arr_2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [21]:
arr+arr_2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [22]:
arr_2-arr


array([[16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16]])

In [23]:
arr*arr_2

array([[ 17,  36,  57,  80],
       [105, 132, 161, 192],
       [225, 260, 297, 336],
       [377, 420, 465, 512]])

#### important function in Numpy for machine learning and data scgiece

#### max()---> it is going to use to calculate the max value inside a matrix or an array
### syntax---> np.max(array)

In [24]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [26]:
max_value=np.max(arr)

In [27]:
max_value

np.int64(16)

In [29]:
ary_data=np.round(np.random.random((4,4))*100).astype('int32')

In [30]:
ary_data

array([[ 29,  52,  72,  31],
       [ 14,  95, 100,   3],
       [ 70,  78,  30,  92],
       [ 80,  39,  10,  56]], dtype=int32)

#### axis ----> it provide us with the idea about the max or min or any operation values inside the specific rows and columns or we get the specific value by row wise or column wise

#### axis=0 ----> column wise operation
#### axis=1 ----> row wise operation

In [31]:
ary_data

array([[ 29,  52,  72,  31],
       [ 14,  95, 100,   3],
       [ 70,  78,  30,  92],
       [ 80,  39,  10,  56]], dtype=int32)

In [ ]:
## column wise
np.max(ary_data,axis=0)

array([ 80,  95, 100,  92], dtype=int32)

In [ ]:
## row wise
np.max(ary_data,axis=1)

array([ 72, 100,  92,  80], dtype=int32)

#### min()----> it will be used for calculating the minimum value from the matrix or array

In [34]:
np.min(ary_data)

np.int32(3)

In [35]:
np.min(ary_data,axis=0)

array([14, 39, 10,  3], dtype=int32)

#### sum()---> calculate the sum of all of the values of a given matrix
### syntax --->np.sum() 

In [36]:
np.sum(ary_data)

np.int64(851)

In [37]:
np.sum(ary_data,axis=1)

array([184, 212, 270, 185])

In [38]:
np.sum(ary_data,axis=0)

array([193, 264, 212, 182])

#### prod()---> it helps with calculating the product of all values inside the matrix
### syntax--> np.prod()

In [39]:
np.prod(ary_data)

np.int64(-5117117470345265152)

In [40]:
np.prod(ary_data,axis=1)

array([ 3365856,   399000, 15069600,  1747200])

In [41]:
ary_data

array([[ 29,  52,  72,  31],
       [ 14,  95, 100,   3],
       [ 70,  78,  30,  92],
       [ 80,  39,  10,  56]], dtype=int32)

In [42]:
np.prod(ary_data)

np.int64(-5117117470345265152)

#### it cross the integer size or overflow the size that why it is negative

#### When the true result exceeds the maximum int64 value, the bits "wrap around" according to two's complement representation, which can produce a negative number.