#### statistical function
#### mean()--->syntex for mean()--->np.mean()
#### mean of all values inside the array or matrix


In [2]:
import numpy as np
ary_data=np.round(np.random.random((4,4))*100).astype('int32')

In [3]:
ary_data

array([[69, 30, 78, 24],
       [66, 66, 31,  1],
       [12, 38, 29, 63],
       [40, 57, 18, 77]], dtype=int32)

In [4]:
np.mean(ary_data,axis=1)

array([50.25, 41.  , 35.5 , 48.  ])

#### std()--> it provides with the standard deviation of all the values of the matrix or array

In [5]:
np.std(ary_data)

np.float64(23.660934972016637)

#### axis=0---column wise std
#### axis=1---row wise std
#### median()--->to calculate median of all values in the array or matrix

In [6]:
np.median(ary_data)

np.float64(39.0)

In [7]:
np.median(ary_data,axis=0)

array([53. , 47.5, 30. , 43.5])

#### var---> it helps with calculating the varience of all the values inside the array or matrix

In [8]:
np.var(ary_data)

np.float64(559.83984375)

## Trignometric functions

#### sin()--->sin value for the value we are going to pass inside it

In [9]:
np.sin(0)

np.float64(0.0)

In [10]:
np.tan(45)

np.float64(1.6197751905438615)

In [11]:
np.cos(12)

np.float64(0.8438539587324921)

#### Dot product of matrices
#### syntex for dot product---> np.dot(matrix1,matrix2)

In [12]:
matrix1=np.round(np.random.random((3,4))*100).astype('int32')

In [13]:
matrix2=np.round(np.random.random((4,3))*100).astype('int32')

In [14]:
matrix1

array([[91,  7, 95, 11],
       [53, 97, 62, 30],
       [23, 29, 90, 75]], dtype=int32)

In [15]:
matrix2

array([[51, 83, 94],
       [ 6, 53, 70],
       [58, 54, 62],
       [ 5, 20,  8]], dtype=int32)

In [16]:
np.dot(matrix1,matrix2)

array([[10248, 13274, 15022],
       [ 7031, 13488, 15856],
       [ 6942,  9806, 10372]], dtype=int32)